<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.7/dist/tailwind.min.css">
    <title>Create Task</title>
</head>
<body style="background-color: #bbbbf5;">
    <main class="container mx-auto mt-10 lg:mt-20">
        <div class="flex justify-between items-center mb-6">
            <!-- Boton para volver al index -->
            <a href="<?= WEB_ROOT ?>/" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" style="background-color:#282854;">Home</a>
            <div class="text-4xl font-bold text-black mb-8 mt-10 text-center">CREATE TASK</div>
            <!-- Boton para volver a tasks list -->
            <a href="<?= WEB_ROOT ?>/tasksList" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" style="background-color:#282854;">Tasks List</a>
        </div>
        <!-- Formulario crear tarea -->
        <div class="bg-gray-100 shadow-md rounded-3xl px-8 pt-6 pb-8 mb-4">
            <form action="/insertTask" method="post" class="w-full max-w-md mx-auto">
                <!-- Task -->
                <div class="mb-4"> 
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="taskName">Task:</label>
                    <input type="text" name="taskName" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Task:">
                </div>
                <!-- Status -->
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="status">Status:</label>
                    <select name="status" class="block appearance-none w-full bg-white border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="status" placeholder="Status:">
                        <option value="TO_DO">To Do</option>
                        <option value="IN_PROGRESS">In Progress</option>
                        <option value="DONE">Done</option>
                    </select>
                </div>
                <!-- Created date -->
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="creationDate">Creation Date:</label>
                    <input type="datetime-local" name="creationDate" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" >
                </div>
                <!-- Deadline -->
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="deadline">Deadline:</label>
                    <input type="datetime-local" name="deadline"  class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                </div>
                <!-- Created by -->
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="createdBy">Created By:</label>
                    <input type="text" name="createdBy" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Created By:">
                </div>
                <!-- Boton submit update -->
                <div class="flex justify-center">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Create Task</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>
