<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TO DO LIST</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
 
</head>
<body style="background-color: #bbbbf5;">

<main class="container mx-auto mt-10 lg:mt-20">
    <div class="w-full max-w-md mx-auto" >
        <div class="bg-white shadow-md rounded-3xl px-6 pt-6 pb-8 mb-4" style="background-color: #141439;">
            <h1 class="text-center text-2xl font-bold mb-8 text-white">WELCOME TO <br> 'TO DO LIST'</h1>
                <div class="mb-6 text-center">
                    <a href="<?= WEB_ROOT ?>/insertTask" class="bg-gray-200 hover:bg-gray-500 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" >Create New Task</a>    
                
                </div>
                <div class="mb-6 text-center">
                    <a href="<?= WEB_ROOT ?>/tasksList" class="bg-gray-200 hover:bg-gray-500 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" >Show Task List</a>
                </div>
                 
       

        </div>
    </div>
    <div class="text-gray-600 text-center mt-4 text-xs">Thank you for using this app created by Gonzalo and Diega.</div>

</main>

</body>
</html>